//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector.Packaging;
using SimpleInjector;
using Civic.Framework.WebApi.Test.Entities;
using Civic.Framework.WebApi.Test.Interfaces;


namespace Civic.Framework.WebApi.Test.Business
{
    
    public class ExamplePackage : IPackage
    {
        public void RegisterServices(Container container)
        {
    		container.Register<IExampleFacade, ExampleBusinessFacade>(Lifestyle.Scoped);
    
    		var factory = new RequestEntityFactory(container);
    
    		factory.Register<Entity1>("Example","Entity1");
    		factory.Register<Entity2>("Example","Entity2");
    		factory.Register<Entity3>("Example","Entity3");
    		factory.Register<Environment>("Example","Environment");
    
        }
    }
    
}


