//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SAAS.Core.Framework;



using ExampleEntity3 = SAAS.Core.Framework.Test.Entities.Entity3;

namespace SAAS.Core.Framework.Test.Interfaces
{
    

public interface IEntity3Facade : IEntityBusinessFacade<ExampleEntity3>
{
}
}

