//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using SimpleInjector.Packaging;
using SimpleInjector;


namespace Civic.Framework.WebApi.Test.Services
{
    
    public class ExamplePackage : IPackage
    {
        public void RegisterServices(Container container)
        {
    		container.Register<IExample, ExampleService>(Lifestyle.Scoped);
        }
    }
    
}


