//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System.Collections.Generic;
using System.ServiceModel;
using Civic.Framework.WebApi;
using Civic.Framework.WebApi.Test.Entities;


namespace Civic.Framework.WebApi.Test.Services
{
    [ServiceContract(Namespace = "http://example.civic360.com/")]
    public interface IExample : IEntityService,IExampleEntity1,IExampleEntity2,IExampleEntity3,IExampleEnvironment
    {
    }
}

