//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings

using System;
using System.Collections.Generic;
using System.ServiceModel;
using Civic.T4.Entities;

using EnvironmentEntity = Civic.T4.Entities.Environment;
using Entity1Entity = Civic.T4.Entities.Entity1;

namespace Civic.T4.Services
{

    [ServiceContract(Namespace = "http://example.civic360.com/")]
    public interface IExampleEnvironment
    {
        [OperationContract]
        List<EnvironmentEntity> GetPagedEnvironment(int skip, ref int count, bool retCount, string filterBy, string orderBy);

        [OperationContract]
        EnvironmentEntity GetEnvironmentById(Int32 id);

        [OperationContract]
        int AddEnvironment(EnvironmentEntity environment);

        [OperationContract]
        void ModifyEnvironment(EnvironmentEntity environment);

        [OperationContract]
        void RemoveEnvironment(Int32 id);

    }

}


