//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Web.Http;
using Civic.Framework.WebApi.Test.Interfaces;
using Entity2Entity = Civic.Framework.WebApi.Test.Entities.Entity2;

namespace Civic.Framework.WebApi.Test.Controllers
{
    [RoutePrefix("api/example/1.0/Entity2")]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 3.5")]
    public partial class ExampleEntity2Controller : ApiController 
    {
    	private readonly IExampleFacade _facade;
    
    	public ExampleEntity2Controller(IExampleFacade facade)
        {
    		_facade = facade;
        }
    
    	[Route("")]
    	public QueryMetadata<Entity2Entity> Get()
    	{
    		ODataV3QueryOptions options = this.GetOptions();
    		var maxrows = Civic.Framework.WebApi.Configuration.T4Config.GetMaxRows("dbo","entity2");
    		var resultLimit = options.Top < maxrows && options.Top > 0 ? options.Top : maxrows;
    		string orderby = options.ProcessOrderByOptions();
    		var result = _facade.GetPagedEntity2(User as ClaimsPrincipal, options.Skip, ref resultLimit, options.InlineCount, options.Filter, orderby);
    		return new QueryMetadata<Entity2Entity>(result, resultLimit);
    	}
    
    	[Route("{someID}/{ff}")]
    	public QueryMetadata<Entity2Entity> Get( Int32 someID, String ff )
    	{
    		var result = new List<Entity2Entity> { _facade.GetEntity2(User as ClaimsPrincipal,  someID, ff) };
    		return new QueryMetadata<Entity2Entity>(result, 1);
    	}
    
    	[Route("")]
    	public QueryMetadata<Entity2Entity> Post([FromBody]Entity2Entity value)
    	{
    		_facade.SaveEntity2(User as ClaimsPrincipal, value);
    		var result = new List<Entity2Entity> { value };
    		return new QueryMetadata<Entity2Entity>(result, 1);
    	}
    
    	[Route("{someID}/{ff}")]
    	public void Put(Int32 someID, String ff, [FromBody]Entity2Entity value)
    	{
    		_facade.SaveEntity2(User as ClaimsPrincipal, value);
    	}
    
    	[Route("{someID}/{ff}")]
    	public void Delete( Int32 someID, String ff )
    	{
    		_facade.RemoveEntity2(User as ClaimsPrincipal,  someID, ff );
    	}
    }
}

