//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using SimpleInjector;
using Core.Framework;

namespace Core.Framework.Test.Entities
{
    [DataContract(Name = "entity1")]
	[Module(Name = "example")]
	public partial class Entity1 : IEntityIdentity
	{

		[DataMember(Name="name")]
		[PrimaryKey]
		public string Name { get; set; }

		[DataMember(Name="environmentID")]
		public int EnvironmentID { get; set; }

		[DataMember(Name="dte")]
		public DateTime Dte { get; set; }

		[DataMember(Name="dte2")]
		public DateTime? Dte2 { get; set; }

		[DataMember(Name="dble1")]
		public double Dble1 { get; set; }

		[DataMember(Name="dec1")]
		public double Dec1 { get; set; }

		[DataMember(Name = "_key")]
		public string _key 
		{ 
			get {
				return Name.ToString();
			}
			set {
				var keys = value.Split('|');
		
				Name = keys[0];
			}
		}

		[DataMember(Name = "_module")]
		public string _module { get { return "example"; } }
    
		[DataMember(Name = "_entity")]
		public string _entity { get { return "entity1"; } }

		[JsonIgnore]
		public Dictionary<string,object> _extra { get; set; }
	}
}

