//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using SimpleInjector;
using Core.Framework;

namespace Core.Framework.Test.Entities
{
    [DataContract(Name = "installationEnvironment")]
	[Module(Name = "example")]
	public partial class InstallationEnvironment : IEntityIdentity
	{

		[DataMember(Name="environmentCode")]
		[PrimaryKey]
		public string EnvironmentCode { get; set; }

		[DataMember(Name="name")]
		public string Name { get; set; }

		[DataMember(Name="description")]
		public string Description { get; set; }

		[DataMember(Name="isVisible")]
		public string IsVisible { get; set; }

		[DataMember(Name="modified")]
		public DateTime Modified { get; set; }

		[DataMember(Name = "_key")]
		public string _key 
		{ 
			get {
				return EnvironmentCode.ToString();
			}
			set {
				var keys = value.Split('|');
		
				EnvironmentCode = keys[0];
			}
		}

		[DataMember(Name = "_module")]
		public string _module { get { return "example"; } }
    
		[DataMember(Name = "_entity")]
		public string _entity { get { return "installationEnvironment"; } }

		[JsonIgnore]
		public Dictionary<string,object> _extra { get; set; }
	}
}



