//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Civic.Core.Data;
using Civic.T4.Entities;

namespace Civic.T4.Data
{
    internal partial class ExampleData
    {

        public static IDBConnection GetConnection()
        {
            return DatabaseFactory.CreateDatabase("Example");
        }

    }
}


