//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Civic.Core.Data;
using Civic.T4.Entities;

namespace Civic.T4.Data
{
    internal partial class ExampleData
    {

        private static string[] filterFillProperties(string[] fillProperties, string filterBy)
        {
            var list = new List<string>();

            foreach (string name in fillProperties)
            {
                if (!name.Contains(".")) continue;
                if (name.StartsWith(filterBy + "."))
                {
                    var trimName = name.Substring(filterBy.Length + 1);
                    if (!list.Contains(trimName)) list.Add(trimName);
                }
            }

            return list.ToArray();
        }

    }
}


