//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Civic.T4.Entities
{
    [DataContract(Name = "entity1")]
    public partial class Entity1
    {
        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "environmentId")]
        public int EnvironmentId { get; set; }

        [DataMember(Name = "dte")]
        public System.DateTime? Dte { get; set; }

    }
}

