//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Civic.Core.Data;
using Civic.T4.WebApi;

namespace Civic.T4.Entities
{
    [DataContract(Name = "entity1")]
    public partial class Entity1 : IEntity
    {
        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "environmentID")]
        public int EnvironmentID { get; set; }

        [DataMember(Name = "dte")]
        public System.DateTime? Dte { get; set; }


        public Entity1 Copy()
        {
            var copy = new Entity1
                {
                    Name = Name,
                    EnvironmentID = EnvironmentID,
                    Dte = Dte
                };
            return copy;
        }

        public string IdentityID
        {
            get
            {
                return null;
            }
        }

        public void Add(IDBConnection connection)
        {
            Data.ExampleData.AddEntity1(this, connection);
        }

        public void Modify(IDBConnection connection)
        {
            Data.ExampleData.ModifyEntity1(this, connection);
        }

        public void Remove(IDBConnection connection)
        {
            Data.ExampleData.RemoveEntity1(Name, connection);
        }

    }
}

