//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using Core.Framework;



using ExampleEntity2 = Core.Framework.Test.Entities.Entity2;

namespace Core.Framework.Test.Interfaces
{
    

public interface IEntity2Facade : IEntityBusinessFacade<ExampleEntity2>
{
}
}

