//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Civic.Core.Data;
using Civic.Framework.WebApi;

namespace Civic.Framework.WebApi.Test.Entities
{
    [DataContract(Name = "entity2")]
    public partial class Entity2 : IEntity
    {
        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "ff")]
        public string ff { get; set; }


        public Entity2 Copy()
        {
            var copy = new Entity2
                {
                    Id = Id,
                    ff = ff
                };
            return copy;
        }

        public string IdentityID
        {
            get
            {
                return this.Id.ToString();
            }
        }

        public void Add(IDBConnection connection)
        {
            var service = new Services.ExampleService();
            service.Connection = connection;
            service.AddEntity2(this);
        }

        public void Modify(IDBConnection connection)
        {
            var service = new Services.ExampleService();
            service.Connection = connection;
            service.ModifyEntity2(this);
        }

        public void Remove(IDBConnection connection)
        {
            var service = new Services.ExampleService();
            service.Connection = connection;
            service.RemoveEntity2(Id, ff);
        }

    }
}

