//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Civic.Core.Data;
using Civic.Framework.WebApi;
using Newtonsoft.Json;
using Civic.Framework.WebApi.Test.Interfaces;

namespace Civic.Framework.WebApi.Test.Entities
{
    [DataContract(Name="environment")]
    public partial class Environment : IEntityIdentity
    {
    
    	[DataMember(Name="id")]
        public int ID { get; set; }
    
    	[DataMember(Name="name")]
        public string Name { get; set; }
    
    	public string IdentityID 
        { 
    		get {
    			return ID.ToString();
    		}
    	}
    
        [DataMember(Name = "_module")]
        public string _module { get { return Info.Module; } }
        
        [DataMember(Name = "_entity")]
        public string _entity { get { return Info.Entity; } }
        
        public static IEntityInfo Info = new EntityInfo
    	{
            Module = "dbo",
            Entity = "Environment",
            Name = "dbo.Environment",
            Properties = new Dictionary<string, IEntityPropertyInfo>
            {
    			{"id", new EntityPropertyInfo { Name = "id", Type="int", IsKey=true }},
    			{"name", new EntityPropertyInfo { Name = "name", Type="string", IsNullable=true }},
            }
        };
    
    	private IFacadeEnvironment _facade;
    	public Environment(IFacadeEnvironment facade)
    	{
    		_facade = facade;
    	}
    
    	public IEntityInfo GetInfo() {
    		return Info;
    	}
    
    	public void Load(IEntityRequestContext context) {
    		_facade.GetEnvironment(context,ID);
    	}
    
    	public void Save(IEntityRequestContext context) {
    		_facade.SaveEnvironment(context, this);
    	}
    
    	public void Remove(IEntityRequestContext context) {
    		_facade.RemoveEnvironment(context,ID);
    	}
    }
}

