//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using SAAS.Core.Framework;

using ExampleEnvironment = SAAS.Core.Framework.Test.Entities.Environment;

namespace SAAS.Core.Framework.Test.Business
{
    
	public partial class EnvironmentFacade : EntityBusinessFacade<ExampleEnvironment>
	{
        public EnvironmentFacade(Container container, IEntityRepository<ExampleEnvironment> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
        {
        }
	}
}

