//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector.Packaging;
using SimpleInjector;



namespace SAAS.Core.Framework.Test.Business
{
    

public class ExampleFacadePackage : IPackage
{
    public void RegisterServices(Container container)
    {
		var factory = new EntityCreateFactory(container);

		factory.Register<SAAS.Core.Framework.Test.Interfaces.IEntity1, SAAS.Core.Framework.Test.Entities.Entity1>(SAAS.Core.Framework.Test.Entities.Entity1.Info);
		factory.Register<SAAS.Core.Framework.Test.Interfaces.IEntity2, SAAS.Core.Framework.Test.Entities.Entity2>(SAAS.Core.Framework.Test.Entities.Entity2.Info);
		factory.Register<SAAS.Core.Framework.Test.Interfaces.IEntity3, SAAS.Core.Framework.Test.Entities.Entity3>(SAAS.Core.Framework.Test.Entities.Entity3.Info);
		factory.Register<SAAS.Core.Framework.Test.Interfaces.IEnvironment, SAAS.Core.Framework.Test.Entities.Environment>(SAAS.Core.Framework.Test.Entities.Environment.Info);
		factory.Register<SAAS.Core.Framework.Test.Interfaces.IInstallationEnvironment, SAAS.Core.Framework.Test.Entities.InstallationEnvironment>(SAAS.Core.Framework.Test.Entities.InstallationEnvironment.Info);
		container.Register<SAAS.Core.Framework.Test.Interfaces.IEntity1Facade, Entity1Facade>(Lifestyle.Singleton);
		container.Register<SAAS.Core.Framework.Test.Interfaces.IEntity2Facade, Entity2Facade>(Lifestyle.Singleton);
		container.Register<SAAS.Core.Framework.Test.Interfaces.IEntity3Facade, Entity3Facade>(Lifestyle.Singleton);
		container.Register<SAAS.Core.Framework.Test.Interfaces.IEnvironmentFacade, EnvironmentFacade>(Lifestyle.Singleton);
		container.Register<SAAS.Core.Framework.Test.Interfaces.IInstallationEnvironmentFacade, InstallationEnvironmentFacade>(Lifestyle.Singleton);


    }
}

}



