//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector.Packaging;
using SimpleInjector;



namespace SAAS.Core.Framework.Test.Business
{
    

public class ExampleFacadePackage : IPackage
{
    public void RegisterServices(Container container)
    {
		var factory = new EntityCreateFactory(container);

		factory.Register<SAAS.Core.Framework.Test.Entities.Entity1>(SAAS.Core.Framework.Test.Entities.Entity1.Info);
		factory.Register<SAAS.Core.Framework.Test.Entities.Entity2>(SAAS.Core.Framework.Test.Entities.Entity2.Info);
		factory.Register<SAAS.Core.Framework.Test.Entities.Entity3>(SAAS.Core.Framework.Test.Entities.Entity3.Info);
		factory.Register<SAAS.Core.Framework.Test.Entities.Environment>(SAAS.Core.Framework.Test.Entities.Environment.Info);
		factory.Register<SAAS.Core.Framework.Test.Entities.InstallationEnvironment>(SAAS.Core.Framework.Test.Entities.InstallationEnvironment.Info);


    }
}

}



