//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using SAAS.Core.Framework;
using Newtonsoft.Json;
using SAAS.Core.Framework.Test.Interfaces;

namespace SAAS.Core.Framework.Test.Interfaces
{
    
public interface IEnvironment : IEntityIdentity
{
	 int ID { get; set; }
	 string Name { get; set; }

}
}

