//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using SAAS.Core.Framework;

using ExampleEntity2 = SAAS.Core.Framework.Test.Entities.Entity2;

namespace SAAS.Core.Framework.Test.Business
{
    
	public partial class Entity2Facade : EntityBusinessFacade<ExampleEntity2>,IEntityBusinessFacade<ExampleEntity2>
	{
        public Entity2Facade(Container container, IEntityRepository<ExampleEntity2> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
        {
        }
	}
}

