//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using Core.Framework;

using ExampleEntity1 = Core.Framework.Test.Entities.Entity1;

namespace Core.Framework.Test.Business
{
    
	public partial class Entity1Facade : EntityBusinessFacade<ExampleEntity1>,IEntityBusinessFacade<ExampleEntity1>
	{
        public Entity1Facade(Container container, IEntityRepository<ExampleEntity1> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
        {
        }
	}
}

