//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using Framework.Core;



using IExampleEntity3 = Framework.Core.Test.Interfaces.IEntity3;

namespace Framework.Core.Test.Interfaces
{
    

public interface IEntity3Facade : IEntityBusinessFacade<IExampleEntity3>
{
}
}

