//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using Civic.Framework.WebApi;


using IExampleEntity3 = Civic.Framework.WebApi.Test.Interfaces.IEntity3;

namespace Civic.Framework.WebApi.Test.Interfaces
{
    
    public interface IEntity3Facade : IEntityBusinessFacade<IExampleEntity3>
    {
    }
}

