//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Security.Claims;
using Civic.Framework.WebApi.Test.Entities;

using Entity1Entity = Civic.Framework.WebApi.Test.Entities.Entity1;

namespace Civic.Framework.WebApi.Test.Interfaces
{
    
    public interface IOperationEntity1
    {
    	List<Entity1Entity> GetPagedEntity1(IEntityRequestContext context, int skip, ref int count, bool retCount, string filterBy, string orderBy );
    
    	Entity1Entity GetEntity1(IEntityRequestContext context,  String name );
    
    	void AddEntity1(IEntityRequestContext context, Entity1Entity entity1 );
    
    	void ModifyEntity1(IEntityRequestContext context, Entity1Entity entity1 );
    
    	void RemoveEntity1(IEntityRequestContext context,  String name );
    }
}

