//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System.Security.Claims;
using SimpleInjector;
using Civic.Core.Data;
using Civic.Framework.WebApi.Test.Interfaces;

namespace Civic.Framework.WebApi.Test.Data.SqlServer
{
    public partial class ExampleRepository : IExampleRepository
    {
    	Container _container;
    
    	public ExampleRepository( Container container ) {
    		_container = container;
    	}
    
    	public Container Container {
    		get {
    			return _container;
    		}
    	}
    }
}

