//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using Civic.Core.Data;
using Civic.Framework.WebApi;
using Civic.Framework.WebApi.Configuration;
using Civic.Framework.WebApi.Test.Entities;

using Entity3Entity = Civic.Framework.WebApi.Test.Entities.Entity3;
namespace Civic.Framework.WebApi.Test.Data
{
    internal partial class ExampleData
    {
    
    	internal static Entity3Entity GetEntity3( String someUID, IDBConnection database)
    	{
            Debug.Assert(database!=null);
    
    		var entity3Returned = new Entity3Entity();
    
    		using (var command = database.CreateStoredProcCommand("dbo","usp_Entity3Get"))
    		{
    			command.AddInParameter("@someUID", someUID);
    			
                command.ExecuteReader(dataReader =>
                    {
                        if (populateEntity3(entity3Returned, dataReader))
                        {
    					entity3Returned.SomeUID = someUID;
    					                    }
                        else entity3Returned = null;
                    });
    		}
    
    		return entity3Returned;
    	}
    
    	internal static List<Entity3Entity> GetPagedEntity3(int skip, ref int count, bool retCount, string filterBy, string orderBy, IDBConnection database)
    	{ 
            Debug.Assert(database!=null);
    
    		var list = new List<Entity3Entity>();
    
    		using (var command = database.CreateStoredProcCommand("dbo","usp_Entity3GetFiltered"))
    		{
                command.AddInParameter("@skip", skip);			
                command.AddInParameter("@retcount", retCount);
    			if(!string.IsNullOrEmpty(filterBy)) command.AddInParameter("@filterBy", filterBy);
    			command.AddInParameter("@orderBy", orderBy);
        		command.AddParameter("@count", ParameterDirection.InputOutput, count);
    			
                command.ExecuteReader(dataReader =>
                    {
    					var item = new Entity3Entity();
    					while(populateEntity3(item, dataReader))
    					{
    						list.Add(item);
    						item = new Entity3Entity();
    					} 
                    });
    
    			if (retCount) count = int.Parse(command.GetOutParameter("@count").Value.ToString());
    		}
    
    		return list;
    	}
    
    	internal static void AddEntity3(Entity3Entity entity3, IDBConnection database)
    	{ 
            Debug.Assert(database!=null);
    
    		using (var command = database.CreateStoredProcCommand("dbo","usp_Entity3Add"))
    		{
    			buildEntity3CommandParameters( entity3, command, true ); 
    			entity3.SomeUID = entity3.SomeUID.InsureUID(); 
    			command.ExecuteNonQuery();
    		}
    	}
    
    	internal static List<Entity3Entity> ModifyEntity3(Entity3Entity entity3, IDBConnection database)
    	{ 
            Debug.Assert(database!=null);
    
    		var list = new List<Entity3Entity>();
    
    		using (var command = database.CreateStoredProcCommand("dbo","usp_Entity3Modify"))
    		{
    			buildEntity3CommandParameters( entity3, command, false );
    			command.ExecuteNonQuery();
    		}
    
    		return list;
    	}
    
    	internal static void RemoveEntity3( String someUID, IDBConnection database )
    	{
            Debug.Assert(database!=null);
    
    		using (var command = database.CreateStoredProcCommand("dbo","usp_Entity3Remove"))
    		{
    			command.AddInParameter("@someUID", someUID);
    			command.ExecuteNonQuery();
    		}
    	}
    
    	private static void buildEntity3CommandParameters( Entity3Entity entity, IDBCommand command, bool addRecord )
    	{ 
            Debug.Assert(command!=null);
    		command.AddInParameter("@someuid", entity.SomeUID.ToUpper());
       		if(addRecord) command.AddParameter("@someid", ParameterDirection.InputOutput,  entity.SomeID);
    		else command.AddInParameter("@someid", entity.SomeID);
    		command.AddInParameter("@otherdate", entity.OtherDate.ToDB());
    
    	}
    	
    	private static bool populateEntity3(Entity3Entity entity, IDataReader dataReader)
    	{
    		if (dataReader==null || !dataReader.Read()) return false;
    							
    		entity.SomeUID = dataReader["SomeUID"] != null && !string.IsNullOrEmpty(dataReader["SomeUID"].ToString()) ? dataReader["SomeUID"].ToString() : string.Empty;						
    		entity.SomeID = dataReader["SomeID"] != null && !(dataReader["SomeID"] is DBNull) ? Int64.Parse(dataReader["SomeID"].ToString()) : 0;					
    		if(!(dataReader["Modified"] is DBNull)) entity.Modified = DateTime.Parse(dataReader["Modified"].ToString()).FromDB();					
    		if(!(dataReader["OtherDate"] is DBNull)) entity.OtherDate = DateTime.Parse(dataReader["OtherDate"].ToString()).FromDB();		
    
    		return true;
    	}
    }
}

