//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using Civic.Framework.WebApi;
using Civic.Framework.WebApi.Test.Interfaces;


using IExampleEntity3 = Civic.Framework.WebApi.Test.Interfaces.IEntity3;
namespace Civic.Framework.WebApi.Test.Business
{
    
    public partial class Entity3Facade : EntityBusinessFacade<IExampleEntity3>, IEntity3Facade
    {
    
            public Entity3Facade(Container container, IEntityRepository<IExampleEntity3> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
            {
            }
    
    }
}

