
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using Civic.Framework.WebApi;
using Civic.Framework.WebApi.Test.Interfaces;


using IExampleEnvironment = Civic.Framework.WebApi.Test.Interfaces.IEnvironment;

namespace Civic.Framework.WebApi.Test.Business
{

    public partial class EnvironmentFacade : EntityBusinessFacade<IExampleEnvironment>
    {
    
            public EnvironmentFacade(Container container, IEntityRepository<IExampleEnvironment> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
            {
            }
    
    }

}

