//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Security.Claims;
using System.Collections.Generic;
using Civic.Core.Logging;
using Civic.Framework.WebApi.Test.Interfaces;


using IExampleEnvironment = Civic.Framework.WebApi.Test.Interfaces.IEnvironment;
namespace Civic.Framework.WebApi.Test.Business
{
    
    public partial class EnvironmentFacade : IEntityBusinessFacade<IExampleEnvironment>
    {
            private readonly IEntityRepository<IExampleEnvironment> _repository;
            private readonly IEntityEventHandlerFactory _handlers;
    		private readonly IEntityCreateFactory _factory;
    
            public EnvironmentFacade(IEntityRepository<IExampleEnvironment> repository, IEntityCreateFactory factory, IEntityEventHandlerFactory handlers)
            {
                _repository = repository;
                _handlers = handlers;
                _factory = factory;
            }
    
            public IExampleEnvironment Get(IEntityRequestContext context, IExampleEnvironment entity) 
        	{
                using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(EnvironmentFacade), "Get")) {
        
    			    var info = entity.GetInfo();
    
        			try {	
        				if (!_handlers.OnGetBefore(context, info))
        					return null;
        
    					entity = _repository.Get(context, entity);
    
        				if (!_handlers.OnGetAfter(context, info, entity))
        					return null;
        
        				return entity;
        			}
        			catch (Exception ex)
        			{
        				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
        			}
        
        		}
        
        		return null;
        	}
        	
        	public IEnumerable<IExampleEnvironment> GetPaged(IEntityRequestContext context, IEntityInfo info, int skip, ref int count, bool retCount, string filterBy, string orderBy) 
        	{
                using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(EnvironmentFacade), "GetPaged")) {
        
        			try {
        				if (!_handlers.OnGetPagedBefore(context, info))
        					return null;
        
        				var list = _repository.GetPaged(context, info, skip, ref count, retCount, filterBy, orderBy);
        
        				list = _handlers.OnGetPagedAfter(context, info, list);
        
        				return list;
        			}
        			catch (Exception ex)
        			{
        				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
        			}
        
        		}
        
        		return null;
        	}
        
        	public void Save(IEntityRequestContext context, IExampleEnvironment entity) 
        	{
                using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(EnvironmentFacade), "Save")) {
            		var first = context.Operations.Count == 0;
        
        			try {
            			var before = _repository.Get(context, entity);
        
        			    if (before == null)
        			    {
        					if (!_handlers.OnAddBefore(context, entity.GetInfo(), entity))
    					        throw new Exception("OnAddBefore handler rejected");
    
                            _repository.Add(context, entity);
        
        					if (!_handlers.OnAddAfter(context, entity.GetInfo(), entity))
    			                throw new Exception("OnAddAfter handler rejected");
                        }
                        else
        			    {
        					if (!_handlers.OnModifyBefore(context, entity.GetInfo(), before, entity))
    					        throw new Exception("OnModifyBefore handler rejected");
    
                            _repository.Modify(context, before, entity);
        
        					if (!_handlers.OnModifyAfter(context, entity.GetInfo(), before, entity))
    			                throw new Exception("OnModifyAfter handler rejected");
                        }
                    }
                    catch (Exception ex)
                    {
                        context.Rollback();
                        if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
                    }
                    finally
                    {
                        if (first)
                        {
                            context.Commit();
                        }
                    }
            	}
        	}
        
        	public void Remove(IEntityRequestContext context, IExampleEnvironment entity ) 
        	{
                using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(EnvironmentFacade), "Remove")) {
                    var first = context.Operations.Count == 0;
        
    				var info = entity.GetInfo();
    
        			try {
        				var before = _repository.Get(context, entity);
        
        				if (!_handlers.OnRemoveBefore(context, info, before))
    				        throw new Exception("OnRemoveBefore handler rejected");
    
                        _repository.Remove(context, before);
        
        				if (!_handlers.OnRemoveAfter(context, info, before))
    			            throw new Exception("OnRemoveAfter handler rejected");
        			}
                    catch (Exception ex)
                    {
                        context.Rollback();
                        if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
                    }
                    finally
                    {
                        if (first)
                        {
                            context.Commit();
                        }
                    }
        
        		}
        	}
    
            public IEnumerable<IExampleEnvironment> GetPaged(ClaimsPrincipal who, IEntityInfo info, int skip, ref int count, bool retCount, string filterBy, string orderBy)
            {
                return GetPaged(new EntityRequestContext { Who = who }, info, skip, ref count, retCount, filterBy, orderBy);
            }
        
        	public IExampleEnvironment Get(ClaimsPrincipal who, IExampleEnvironment entity) {
        		return Get(new EntityRequestContext {Who = who}, entity);
        	}
        
        	public void Save(ClaimsPrincipal who, IExampleEnvironment entity) {
        		Save(new EntityRequestContext {Who = who}, entity);
        	}
        
        	public void Remove(ClaimsPrincipal who, IExampleEnvironment entity ) {
        		Remove(new EntityRequestContext {Who = who}, entity);
        	}
    }
}

