//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using Civic.Framework.WebApi.Test.Interfaces;

namespace Civic.Framework.WebApi.Test.Business
{
    
    public partial class ExampleBusinessFacade : IExampleFacade
    {
    	private readonly IExampleRepository _respository;
        private readonly IEntityEventHandlerFactory _handlers;
    
    	public ExampleBusinessFacade(IExampleRepository respository, IEntityEventHandlerFactory handlers) 
    	{
    		_respository = respository;
            _handlers = handlers;
    	}
    }
}

