//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector.Packaging;
using SimpleInjector;
using Civic.Framework.WebApi.Test.Entities;
using Civic.Framework.WebApi.Test.Interfaces;


namespace Civic.Framework.WebApi.Test.Business
{
    
    public class ExamplePackage : IPackage
    {
        public void RegisterServices(Container container)
        {
    		container.Register<IExampleFacade, ExampleBusinessFacade>(Lifestyle.Scoped);
    
    		var factory = new EntityCreateFactory(container);
    
    		factory.Register<Entity1>(Entity1.Info);
    		factory.Register<Entity2>(Entity2.Info);
    		factory.Register<Entity3>(Entity3.Info);
    		factory.Register<Environment>(Environment.Info);
    		factory.Register<InstallationEnvironment>(InstallationEnvironment.Info);
    
        }
    }
    
}


