//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector.Packaging;
using SimpleInjector;


namespace Civic.Framework.WebApi.Test.Business
{
    
    public class ExampleFacadePackage : IPackage
    {
        public void RegisterServices(Container container)
        {
    		var factory = new EntityCreateFactory(container);
    
    		factory.Register<Civic.Framework.WebApi.Test.Entities.Entity1>(Civic.Framework.WebApi.Test.Entities.Entity1.Info);
    		factory.Register<Civic.Framework.WebApi.Test.Entities.Entity2>(Civic.Framework.WebApi.Test.Entities.Entity2.Info);
    		factory.Register<Civic.Framework.WebApi.Test.Entities.Entity3>(Civic.Framework.WebApi.Test.Entities.Entity3.Info);
    		factory.Register<Civic.Framework.WebApi.Test.Entities.Environment>(Civic.Framework.WebApi.Test.Entities.Environment.Info);
    		factory.Register<Civic.Framework.WebApi.Test.Entities.InstallationEnvironment>(Civic.Framework.WebApi.Test.Entities.InstallationEnvironment.Info);
    		container.Register<IEntityBusinessFacade<Civic.Framework.WebApi.Test.Interfaces.IEntity1>, Entity1Facade>(Lifestyle.Singleton);
    		container.Register<IEntityBusinessFacade<Civic.Framework.WebApi.Test.Interfaces.IEntity2>, Entity2Facade>(Lifestyle.Singleton);
    		container.Register<IEntityBusinessFacade<Civic.Framework.WebApi.Test.Interfaces.IEntity3>, Entity3Facade>(Lifestyle.Singleton);
    		container.Register<IEntityBusinessFacade<Civic.Framework.WebApi.Test.Interfaces.IEnvironment>, EnvironmentFacade>(Lifestyle.Singleton);
    		container.Register<IEntityBusinessFacade<Civic.Framework.WebApi.Test.Interfaces.IInstallationEnvironment>, InstallationEnvironmentFacade>(Lifestyle.Singleton);
    
        }
    }
    
}


