//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Security.Claims;
using System.Collections.Generic;
using Civic.Core.Security;
using Civic.Core.Logging;

using Entity2Entity = Civic.Framework.WebApi.Test.Entities.Entity2;

namespace Civic.Framework.WebApi.Test.Business
{
    
    public partial class ExampleBusinessFacade
    {
    
    	public Entity2Entity GetEntity2(IEntityRequestContext context,  Int32 someID, String ff) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "GetEntity2")) {
    
    			try {	
    				if (!_handlers.OnGetBefore(context, Entity2Entity.Info))
    					return null;
    
    				var entity = _respository.GetEntity2(context,  someID, ff);
    				
    				if (!_handlers.OnGetAfter(context, Entity2Entity.Info, entity))
    					return null;
    
    				return entity;
    			}
    			catch (Exception ex)
    			{
    				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
    			}
    
    		}
    
    		return null;
    	}
    	
    	public List<Entity2Entity> GetPagedEntity2(IEntityRequestContext context, int skip, ref int count, bool retCount, string filterBy, string orderBy) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "GetPagedEntity2")) {
    
    			try {
    				if (!_handlers.OnGetPagedBefore(context, Entity2Entity.Info))
    					return null;
    
    				var list = _respository.GetPagedEntity2(context, skip, ref count, retCount, filterBy, orderBy);
    
    				list = _handlers.OnGetPagedAfter<Entity2Entity>(context, Entity2Entity.Info, list);
    
    				return list;
    			}
    			catch (Exception ex)
    			{
    				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
    			}
    
    		}
    
    		return null;
    	}
    
    	public void SaveEntity2(IEntityRequestContext context, Entity2Entity entity) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "SaveEntity2")) {
        		try {
        			var before = _respository.GetEntity2(context,  entity.SomeID, entity.ff);
    
    			    if (before == null)
    			    {
    					if (!_handlers.OnAddBefore(context, Entity2Entity.Info, entity))
    						return;
    
                        _respository.AddEntity2(context, entity);
    
    					if (!_handlers.OnAddAfter(context, Entity2Entity.Info, entity))
    						return;
                    }
    			    else
    			    {
    					if (!_handlers.OnModifyBefore(context, Entity2Entity.Info, before, entity))
    						return;
    
    			        _respository.ModifyEntity2(context, entity);
    
    					if (!_handlers.OnModifyAfter(context, Entity2Entity.Info, before, entity))
    						return;
                    }
        		}
        		catch (Exception ex)
        		{
        			if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
        		}
        	}
    	}
    
    	public void RemoveEntity2(IEntityRequestContext context,  Int32 someID, String ff ) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "RemoveEntity2")) {
    
    			try {
    				var before = _respository.GetEntity2(context,  someID, ff);
    
    				if (!_handlers.OnRemoveBefore(context, Entity2Entity.Info, before))
    					return;
    
    				_respository.RemoveEntity2(context,  someID, ff);
    
    				if (!_handlers.OnRemoveAfter(context, Entity2Entity.Info, before))
    					return;
    			}
    			catch (Exception ex)
    			{
    				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
    			}
    
    		}
    	}
    
    	public List<Entity2Entity> GetPagedEntity2(ClaimsPrincipal who, int skip, ref int count, bool retCount, string filterBy, string orderBy) {
    		return GetPagedEntity2(new EntityRequestContext {Who = who}, skip, ref count, retCount, filterBy, orderBy);
    	}
    
    	public Entity2Entity GetEntity2(ClaimsPrincipal who, Int32 someID, String ff ) {
    		return GetEntity2(new EntityRequestContext {Who = who}, someID, ff);
    	}
    
    	public void SaveEntity2(ClaimsPrincipal who, Entity2Entity entity) {
    		SaveEntity2(new EntityRequestContext {Who = who}, entity);
    	}
    
    	public void RemoveEntity2(ClaimsPrincipal who, Int32 someID, String ff ) {
    		RemoveEntity2(new EntityRequestContext {Who = who}, someID, ff);
    	}
    
    }
}

