//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using System;
using System.Security.Claims;
using System.Collections.Generic;
using Civic.Core.Security;
using Civic.Core.Logging;

using EnvironmentEntity = Civic.Framework.WebApi.Test.Entities.Environment;

namespace Civic.Framework.WebApi.Test.Business
{
    
    public partial class ExampleBusinessFacade
    {
    
    	public EnvironmentEntity GetEnvironment(IEntityRequestContext context,  Int32 id) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "GetEnvironment")) {
    
    			try {	
    				if (!_handlers.OnGetBefore(context, EnvironmentEntity.Info))
    					return null;
    
    				var entity = _respository.GetEnvironment(context,  id);
    				
    				if (!_handlers.OnGetAfter(context, EnvironmentEntity.Info, entity))
    					return null;
    
    				return entity;
    			}
    			catch (Exception ex)
    			{
    				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
    			}
    
    		}
    
    		return null;
    	}
    	
    	public List<EnvironmentEntity> GetPagedEnvironment(IEntityRequestContext context, int skip, ref int count, bool retCount, string filterBy, string orderBy) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "GetPagedEnvironment")) {
    
    			try {
    				if (!_handlers.OnGetPagedBefore(context, EnvironmentEntity.Info))
    					return null;
    
    				var list = _respository.GetPagedEnvironment(context, skip, ref count, retCount, filterBy, orderBy);
    
    				list = _handlers.OnGetPagedAfter<EnvironmentEntity>(context, EnvironmentEntity.Info, list);
    
    				return list;
    			}
    			catch (Exception ex)
    			{
    				if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
    			}
    
    		}
    
    		return null;
    	}
    
    	public void SaveEnvironment(IEntityRequestContext context, EnvironmentEntity entity) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "SaveEnvironment")) {
        		var first = context.Operations.Count == 0;
    
    			try {
        			var before = _respository.GetEnvironment(context,  entity.ID);
    
    			    if (before == null)
    			    {
    					if (!_handlers.OnAddBefore(context, EnvironmentEntity.Info, entity))
    						return;
    
                        _respository.AddEnvironment(context, entity);
    
    					if (!_handlers.OnAddAfter(context, EnvironmentEntity.Info, entity))
    						return;
                    }
    			    else
    			    {
    					if (!_handlers.OnModifyBefore(context, EnvironmentEntity.Info, before, entity))
    						return;
    
    			        _respository.ModifyEnvironment(context, entity);
    
    					if (!_handlers.OnModifyAfter(context, EnvironmentEntity.Info, before, entity))
    						return;
                    }
        		}
                catch (Exception ex)
                {
                    context.Rollback();
                    if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
                }
                finally
                {
                    if (first)
                    {
                        context.Commit();
                    }
                }
        	}
    	}
    
    	public void RemoveEnvironment(IEntityRequestContext context,  Int32 id ) 
    	{
            using(Logger.CreateTrace(LoggingBoundaries.ServiceBoundary, typeof(ExampleBusinessFacade), "RemoveEnvironment")) {
                var first = context.Operations.Count == 0;
    
    			try {
    				var before = _respository.GetEnvironment(context,  id);
    
    				if (!_handlers.OnRemoveBefore(context, EnvironmentEntity.Info, before))
    					return;
    
    				_respository.RemoveEnvironment(context, before);
    
    				if (!_handlers.OnRemoveAfter(context, EnvironmentEntity.Info, before))
    					return;
    			}
                catch (Exception ex)
                {
                    context.Rollback();
                    if (Logger.HandleException(LoggingBoundaries.ServiceBoundary, ex)) throw;
                }
                finally
                {
                    if (first)
                    {
                        context.Commit();
                    }
                }
    
    		}
    	}
    
    	public List<EnvironmentEntity> GetPagedEnvironment(ClaimsPrincipal who, int skip, ref int count, bool retCount, string filterBy, string orderBy) {
    		return GetPagedEnvironment(new EntityRequestContext {Who = who}, skip, ref count, retCount, filterBy, orderBy);
    	}
    
    	public EnvironmentEntity GetEnvironment(ClaimsPrincipal who, Int32 id ) {
    		return GetEnvironment(new EntityRequestContext {Who = who}, id);
    	}
    
    	public void SaveEnvironment(ClaimsPrincipal who, EnvironmentEntity entity) {
    		SaveEnvironment(new EntityRequestContext {Who = who}, entity);
    	}
    
    	public void RemoveEnvironment(ClaimsPrincipal who, Int32 id ) {
    		RemoveEnvironment(new EntityRequestContext {Who = who}, id);
    	}
    
    }
}

