//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Civic.Framework.WebApi.Test.Interfaces;

namespace Civic.Framework.WebApi.Test.Business
{
    
    public partial class ExampleBusinessFacade : IExampleFacade
    {
    	private readonly IExampleRepository _respository;
    	public ExampleBusinessFacade(IExampleRepository respository) 
    	{
    		_respository = respository;
    	}
    }
}

