//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using Framework.Core;
using Framework.Core.Test.Interfaces;



using IExampleEntity3 = Framework.Core.Test.Interfaces.IEntity3;
namespace Framework.Core.Test.Business
{
    

public partial class Entity3Facade : EntityBusinessFacade<IExampleEntity3>, IEntity3Facade
{

        public Entity3Facade(Container container, IEntityRepository<IExampleEntity3> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
        {
        }

}
}

