//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is to supress no xml comments in public members warnings 

using SimpleInjector;
using Framework.Core;
using Framework.Core.Test.Interfaces;



using IExampleInstallationEnvironment = Framework.Core.Test.Interfaces.IInstallationEnvironment;
namespace Framework.Core.Test.Business
{
    

public partial class InstallationEnvironmentFacade : EntityBusinessFacade<IExampleInstallationEnvironment>, IInstallationEnvironmentFacade
{

        public InstallationEnvironmentFacade(Container container, IEntityRepository<IExampleInstallationEnvironment> repository, IEntityEventHandlerFactory handlers) : base(container, repository, handlers)
        {
        }

}
}

